#!/bin/bash

statush=$(curl -Is https://agent.callpay.com/site/health | head -n 1)

sleep 6

RESULT=$?

status200=$(echo $statush | grep -o 200)
status302=$(echo $statush | grep -o 302)


if [[ $status200 == "200" ]];
		then
		echo "200"
elif [[ $status302 == "302" ]];
		then
		echo "302"
else
echo $statush Error
echo $RESULT
exit 1
fi

exit 0


